services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      RAILS_ENV: development

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules  # ← これを追加して、node_modules をホストと共有しない
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
